import { Inter } from "next/font/google";
import "./globals.css";
import {Providers} from './providers'
import {Penegalactico} from './components/navbar'


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="absolute inset-0 -z-10 h-full w-full items-center [background:radial-gradient(125%_125%_at_50%_10%,#000_40%,#63e_100%)]" >
        <Providers>
          <Penegalactico/>
        {children}
        </Providers>
        </body>
    </html>
  );
}
